# Используйте официальный образ PostgreSQL
FROM postgres:latest

# Установите переменные окружения для имени пользователя, пароля и имени базы данных
ENV POSTGRES_USER=backend
ENV POSTGRES_PASSWORD=mypassword
ENV POSTGRES_DB=version
