version: '3'
services:
  # Сервис для вашего приложения NestJS
  nest-app:
    image: node:20
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: npm run dev
    ports:
      - '3000:3000'
    depends_on:
      - db

  # Сервис для базы данных PostgreSQL
  db:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5432:5432'
