# Используйте официальный образ PostgreSQL
FROM postgres:13

# Установите пароль для пользователя postgres
ENV POSTGRES_PASSWORD=yourpassword

# Создайте базу данных с именем yourdbname
ENV POSTGRES_DB=yourdbname

# Установите имя пользователя
ENV POSTGRES_USER=youruser

# Откройте порт 5432
EXPOSE 5432
